version: '3.5'

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.18-rc0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db

networks:
  default:
    name: genaifinder