version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.18-rc0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:

networks:
  default:
    name: genaifinder